import re

with open('src/app/context/AppContext.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

en_keys = """
    // New Translations
    'dashboard.typeDistribution': 'Question Type Distribution',
    'dashboard.noData': 'No data available',
    'dashboard.quantity': 'Quantity',
    
    'common.success': 'Success',
    'common.error': 'Error',
    'common.info': 'Information',

    'exam.management': 'Exam Management',
    'exam.managementDesc': 'View, edit and manage all generated exams',
    'exam.createNew': 'Create New Exam',
    'exam.searchPlaceholder': 'Search exams...',
    'exam.totalExams': 'Total Exams',
    'exam.durationLabel': 'Duration',
    'exam.all': 'All',
    'exam.duration_60': '<= 60 min',
    'exam.duration_90': '61 - 90 min',
    'exam.duration_120': '91 - 120 min',
    'exam.duration_more': '> 120 min',
    'exam.numQuestionsFilter': 'Number of questions (from - to)',
    'exam.from': 'From',
    'exam.to': 'To',
    'exam.noExams': 'No exams available',
    'exam.clickToStart': 'Click "Create New Exam" to get started',
    'exam.name': 'Exam Name',
    'exam.numQuestions': 'Questions',
    'exam.createdAt': 'Created At',
    'exam.lastEdited': 'Last Edited',
    'exam.actions': 'Actions',
    'exam.questions': 'questions',
    'exam.minutes': 'minutes',
    'exam.previewTitle': 'Preview',
    'exam.exportTitle': 'Export File',
    'exam.deleteTitle': 'Delete',
    'exam.confirmDelete': 'Confirm delete exam',
    'exam.confirmDeleteMessage': 'Are you sure you want to delete exam "{title}"? This action cannot be undone.',
    'exam.exportFormatTitle': 'Select Export Format',
    'exam.exportFailed': 'Failed to export {format} file!',
    'exam.exportSuccess': 'Successfully exported {format} file! Download is starting.',
    'exam.savedSuccess': 'Exam confirmed and saved successfully! Interface will refresh...',
    'exam.saveDraftSuccess': 'Draft saved successfully!',
    'exam.saveError': 'Error saving exam.',
    'exam.draftError': 'Error saving draft.',
    'exam.changeQuestion': 'Change Question',
    'exam.correctAnswer': 'Correct Answer',
    'exam.explanation': 'Explanation',
    'exam.sampleAnswer': 'Sample Answer',
    'exam.notUpdated': 'Not updated',
    'exam.gradingRubric': 'Grading Rubric',
    'exam.noAlternativeQuestion': 'No alternative questions available in the Bank matching the criteria. Please add more questions.',
    'exam.questionIndex': 'Question {index}',

    'blueprint.missingDetails': 'Missing questions details:',
    'blueprint.continueOrAdd': 'Do you want to continue saving the Blueprint or go to the Question Bank to add more questions?',
    'blueprint.goToGen': 'Go to AI Generation',
    'blueprint.saveAnyway': 'Save Blueprint anyway',
    
    'examGen.selectCourse': 'Select course...',
    'examGen.searchCourse': 'Search course...',
    'examGen.noCourseFound': 'No course found',
    'examGen.validationErrorSelect': 'Please select a valid, approved Blueprint.',
    'examGen.validationErrorNotEnough': 'Not enough questions in the database according to the Blueprint structure. Cannot generate exam.',
    'examGen.generateSuccess': 'Exam generated successfully! Displaying preview...',
    'examGen.generateFailed': 'Exam generation failed. Please check the Question Bank.',
    'examGen.selectBlueprintPlaceholder': '-- Select Blueprint --',
    'examGen.notEnoughLOs': '(Not enough Qs)',
    'examGen.previewDisplay': 'Exam will be displayed here after generation',
    'examGen.previewInstruction': 'Please configure settings on the left and click "Generate Exam" to let AI automatically pull random questions from the bank based on the Blueprint.',
    'examGen.unbalancedLO': 'Unbalanced',
    'examGen.balancedLO': 'Balanced',
    'examGen.veryBalancedLO': 'Very Balanced',
    'examGen.loCovered': 'LO Covered',
"""

vi_keys = """
    // New Translations
    'dashboard.typeDistribution': 'Phân bố loại câu hỏi',
    'dashboard.noData': 'Chưa có dữ liệu câu hỏi',
    'dashboard.quantity': 'Số lượng',

    'common.success': 'Thành công',
    'common.error': 'Lỗi',
    'common.info': 'Thông báo',

    'exam.management': 'Quản lý đề thi',
    'exam.managementDesc': 'Xem, chỉnh sửa và quản lý tất cả các đề thi đã tạo',
    'exam.createNew': 'Tạo đề thi mới',
    'exam.searchPlaceholder': 'Tìm kiếm đề thi...',
    'exam.totalExams': 'Tổng số đề thi',
    'exam.durationLabel': 'Thời lượng',
    'exam.all': 'Tất cả',
    'exam.duration_60': '<= 60 phút',
    'exam.duration_90': '61 - 90 phút',
    'exam.duration_120': '91 - 120 phút',
    'exam.duration_more': '> 120 phút',
    'exam.numQuestionsFilter': 'Số câu hỏi (từ - đến)',
    'exam.from': 'Từ',
    'exam.to': 'Đến',
    'exam.noExams': 'Chưa có đề thi nào',
    'exam.clickToStart': 'Nhấn "Tạo đề thi mới" để bắt đầu',
    'exam.name': 'Tên đề thi',
    'exam.numQuestions': 'Số câu',
    'exam.createdAt': 'Ngày tạo',
    'exam.lastEdited': 'Chỉnh sửa lần cuối',
    'exam.actions': 'Thao tác',
    'exam.questions': 'câu',
    'exam.minutes': 'phút',
    'exam.previewTitle': 'Xem trước',
    'exam.exportTitle': 'Xuất File',
    'exam.deleteTitle': 'Xóa',
    'exam.confirmDelete': 'Xác nhận xóa đề thi',
    'exam.confirmDeleteMessage': 'Bạn có chắc chắn muốn xóa đề thi "{title}"? Hành động này không thể hoàn tác.',
    'exam.exportFormatTitle': 'Chọn định dạng xuất file',
    'exam.exportFailed': 'Xuất file {format} thất bại!',
    'exam.exportSuccess': 'Xuất file {format} thành công! File đang được tải xuống.',
    'exam.savedSuccess': 'Đã xác nhận và lưu đề thi thành công! Giao diện sẽ được làm mới...',
    'exam.saveDraftSuccess': 'Đã lưu bản nháp thành công!',
    'exam.saveError': 'Có lỗi xảy ra khi lưu đề thi.',
    'exam.draftError': 'Có lỗi xảy ra khi lưu bản nháp.',
    'exam.changeQuestion': 'Đổi câu hỏi',
    'exam.correctAnswer': 'Đáp án đúng',
    'exam.explanation': 'Giải thích',
    'exam.sampleAnswer': 'Đáp án mẫu',
    'exam.notUpdated': 'Chưa cập nhật',
    'exam.gradingRubric': 'Rubric chấm điểm',
    'exam.noAlternativeQuestion': 'Không còn câu hỏi tương tự trong Ngân hàng đề đáp ứng điều kiện. Vui lòng bổ sung thêm câu hỏi mới.',
    'exam.questionIndex': 'Câu {index}',

    'blueprint.missingDetails': 'Chi tiết số câu còn thiếu:',
    'blueprint.continueOrAdd': 'Bạn muốn tiếp tục lưu Blueprint hay chuyển sang Ngân hàng đề tạo thêm câu hỏi?',
    'blueprint.goToGen': 'Chuyển sang gen câu hỏi',
    'blueprint.saveAnyway': 'Vẫn lưu Blueprint',

    'examGen.selectCourse': 'Chọn môn học...',
    'examGen.searchCourse': 'Tìm môn học...',
    'examGen.noCourseFound': 'Không tìm thấy môn học',
    'examGen.validationErrorSelect': 'Vui lòng chọn Blueprint (Ma trận đề thi) hợp lệ đã được kiểm duyệt.',
    'examGen.validationErrorNotEnough': 'Không đủ số lượng câu hỏi trong cơ sở dữ liệu theo cấu trúc Blueprint, không thể tạo đề thi.',
    'examGen.generateSuccess': 'Tạo đề thi thành công! Đang hiển thị bản xem trước...',
    'examGen.generateFailed': 'Tạo đề thi thất bại. Vui lòng kiểm tra lại Ngân hàng câu hỏi.',
    'examGen.selectBlueprintPlaceholder': '-- Chọn Ma trận --',
    'examGen.notEnoughLOs': '(Chưa đủ CH)',
    'examGen.previewDisplay': 'Đề thi sẽ được hiển thị sau khi tạo',
    'examGen.previewInstruction': 'Vui lòng thiết lập cấu hình ở bên trái và nhấn nút "Tạo đề thi" để AI tự động lấy câu hỏi ngẫu nhiên từ ngân hàng dựa trên ma trận (Blueprint).',
    'examGen.unbalancedLO': 'Mất cân bằng',
    'examGen.balancedLO': 'Cân bằng',
    'examGen.veryBalancedLO': 'Rất cân bằng',
    'examGen.loCovered': 'Số LO phủ',
"""

content = content.replace("  },\n  vi: {", en_keys + "\n  },\n  vi: {")
content = content.replace("  },\n};", vi_keys + "\n  },\n};")

with open('src/app/context/AppContext.tsx', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done updating AppContext.tsx")
