import re

with open('src/app/context/AppContext.tsx', 'r', encoding='utf-8') as f:
    content = f.read()

en_keys = """
    // AI Generation Extended
    'ai.step1': 'Document Upload',
    'ai.step2': 'Knowledge Extraction',
    'ai.step3': 'LO Understanding',
    'ai.step4': 'Question Generation',
    'ai.step5': 'Pending Review',
    'ai.noCourses': 'No courses are available from the backend yet.',
    'ai.noLOs': 'No learning outcomes are available for this course.',
    'ai.clickToChoose': 'Click to choose a file',
    'ai.fileHint': 'PDF or DOCX, max 15 MB',
    'ai.reuseMaterials': 'Reuse uploaded materials for the selected course.',
    'ai.selectCourseLoad': 'Select a course to load existing documents.',
    'ai.noDocuments': 'No uploaded documents found for this course.',
    'ai.requiredBeforeGen': 'Required before generation.',
    'ai.uploadBeforeExtract': 'Upload a document before extraction.',
    'ai.allowedRange': 'Allowed range: 1-5 questions. Default is 3.',
    'ai.nextStep': 'Next step',
    'ai.noExplanation': 'No explanation/source note was returned.',
    'ai.mcqMissing': 'MCQ options are missing from this response.',
    'ai.notProvided': 'Not provided.',
    'ai.section': 'Section',
    'ai.sourceSession': 'uploaded this session',
    'ai.sourceHistory': 'selected from history',

    // Page Subtitles
    'courses.subtitle': 'Manage course list in the system',
    'lo.subtitle': 'Manage Learning Outcomes for each course',
    'bank.subtitle': 'Manage all questions in the bank',
    'review.subtitle': 'Review questions generated by AI before adding them to the bank',
    'analytics.subtitle': 'Overall statistics and analysis of the system',
"""

vi_keys = """
    // AI Generation Extended
    'ai.step1': 'Tải lên tài liệu',
    'ai.step2': 'Trích xuất kiến thức',
    'ai.step3': 'Phân tích chuẩn đầu ra',
    'ai.step4': 'Tạo câu hỏi',
    'ai.step5': 'Chờ duyệt',
    'ai.noCourses': 'Chưa có khóa học nào trên hệ thống.',
    'ai.noLOs': 'Khóa học này chưa có chuẩn đầu ra nào.',
    'ai.clickToChoose': 'Nhấn để chọn file',
    'ai.fileHint': 'PDF hoặc DOCX, tối đa 15 MB',
    'ai.reuseMaterials': 'Sử dụng lại tài liệu đã tải lên cho khóa học này.',
    'ai.selectCourseLoad': 'Chọn khóa học để xem tài liệu đã có.',
    'ai.noDocuments': 'Không có tài liệu nào cho khóa học này.',
    'ai.requiredBeforeGen': 'Bắt buộc chọn trước khi tạo.',
    'ai.uploadBeforeExtract': 'Tải lên tài liệu trước khi trích xuất.',
    'ai.allowedRange': 'Cho phép 1-5 câu. Mặc định là 3.',
    'ai.nextStep': 'Bước tiếp theo',
    'ai.noExplanation': 'Không có giải thích hoặc nguồn gốc trích xuất.',
    'ai.mcqMissing': 'Thiếu các lựa chọn trắc nghiệm.',
    'ai.notProvided': 'Không có thông tin.',
    'ai.section': 'Phần',
    'ai.sourceSession': 'vừa tải lên',
    'ai.sourceHistory': 'chọn từ lịch sử',

    // Page Subtitles
    'courses.subtitle': 'Quản lý danh sách các khóa học trong hệ thống',
    'lo.subtitle': 'Quản lý chuẩn đầu ra cho từng khóa học',
    'bank.subtitle': 'Quản lý tất cả câu hỏi trong ngân hàng đề',
    'review.subtitle': 'Duyệt câu hỏi do AI tạo trước khi đưa vào ngân hàng',
    'analytics.subtitle': 'Thống kê và phân tích tổng quan toàn hệ thống',
"""

# Insert right before the end of the EN dictionary (which is before `vi: {`)
content = content.replace("  },\n  vi: {", en_keys + "\n  },\n  vi: {")
# Insert right before the end of the VI dictionary (which is before `};`)
content = content.replace("  },\n};", vi_keys + "\n  },\n};")

with open('src/app/context/AppContext.tsx', 'w', encoding='utf-8') as f:
    f.write(content)

print("Done updating AppContext.tsx")
